// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaQA909OQl417KaIt9MzCkvkGrgwrmSFQ',
    appId: '1:41843473703:web:77d90a438175783ecfbd02',
    messagingSenderId: '41843473703',
    projectId: 'care-o-47782',
    authDomain: 'care-o-47782.firebaseapp.com',
    storageBucket: 'care-o-47782.firebasestorage.app',
    measurementId: 'G-6W53PGC55B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3gpJNc4L9nx4sHzV_r8uQL1bw5SKwDDY',
    appId: '1:41843473703:android:b0d2cb8526ce82cfcfbd02',
    messagingSenderId: '41843473703',
    projectId: 'care-o-47782',
    storageBucket: 'care-o-47782.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Fi5FhMHWfsv2pl5XTrXIErix3WSFO9I',
    appId: '1:41843473703:ios:15fb093969343882cfbd02',
    messagingSenderId: '41843473703',
    projectId: 'care-o-47782',
    storageBucket: 'care-o-47782.firebasestorage.app',
    iosBundleId: 'com.example.careoNew1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Fi5FhMHWfsv2pl5XTrXIErix3WSFO9I',
    appId: '1:41843473703:ios:15fb093969343882cfbd02',
    messagingSenderId: '41843473703',
    projectId: 'care-o-47782',
    storageBucket: 'care-o-47782.firebasestorage.app',
    iosBundleId: 'com.example.careoNew1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaQA909OQl417KaIt9MzCkvkGrgwrmSFQ',
    appId: '1:41843473703:web:b30788b9dea78e52cfbd02',
    messagingSenderId: '41843473703',
    projectId: 'care-o-47782',
    authDomain: 'care-o-47782.firebaseapp.com',
    storageBucket: 'care-o-47782.firebasestorage.app',
    measurementId: 'G-30ZRCKQ0V5',
  );
}
